### PR TITLE
fixes to editor.  Now has platform lengthener, and generates json at the end

### PR DESCRIPTION
**Pull request by mksteve**
More to do?

Improve editor to accept the jump point for doors.
Add range to the enemies and toggle movine

### CODE REVIEW

**Review by 12joan — APPROVED** [review]
Thank you very much. I can’t wait to try this.

**Comment by mksteve** [comment]
Updated editor to show target locations for door teleport, and the range of the enemy.

You can change an ememies speed by hovering over and then pressing +/-
You can drag the enemies fly_pos around
You can drag a door’s flypos around
You can delete anything (can’t create a rick).

You can re-size platforms by +/- when hovering over.

You can change movable by M key

Do you want me to check straight into trunk, or do the pull-request




Sent from Mail for Windows 10

**Comment by 12joan** [comment]
Thanks again for continuing to contribute to House Trapped. 

I have invited you to push commits to the repository, so you should be able to upload the changes yourself without creating a pull-request. 

Kind regards.

**Comment by mksteve** [comment]
Will try with next change to do it without pull request.  This seemed to need it, but I could “approve” it myself

Sent from Mail for Windows 10

**Pull request merged**
